import {
  Camera,
  ChevronLeft,
  ChevronRight,
  Command,
  File,
  FileText,
  Github,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Dumbbell,
  LineChart,
  LayoutDashboard,
} from "lucide-react"

export type Icon = typeof Command

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  add: Plus,
  more: MoreVertical,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  camera: Camera,
  image: Image,
  file: File,
  fileText: FileText,
  dumbbell: Dumbbell,
  lineChart: LineChart,
  dashboard: LayoutDashboard,
} 